# Generated by Django 4.1.3 on 2022-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xymogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
