# Generated by Django 4.1.3 on 2022-11-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xyomgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor_id', models.AutoField(primary_key=True, serialize=False)),
                ('flavor_name', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCount',
            fields=[
                ('unit_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_count_name', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='xyomgen/'),
        ),
        migrations.CreateModel(
            name='XyomgenProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('descriptionShort', models.CharField(max_length=255)),
                ('productImage', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('count', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('unitWeight', models.CharField(max_length=255)),
                ('wholesalePrice', models.FloatField()),
                ('retailPrice', models.FloatField()),
                ('releaseDate', models.CharField(max_length=255)),
                ('upc', models.CharField(default='N/A', max_length=255)),
                ('sku', models.CharField(default='N/A', max_length=255)),
                ('warnings', models.CharField(default='N/A', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xproduct_brand', to='xyomgen.brand')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xproduct_flavor', to='xyomgen.flavor')),
                ('unitCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xproduct_unitcount', to='xyomgen.unitcount')),
            ],
        ),
        migrations.CreateModel(
            name='XProductCategoryMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcatmap_product', to='xyomgen.xyomgenproduct')),
            ],
        ),
    ]
