# Generated by Django 4.1.3 on 2022-11-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyomgen', '0002_brand_category_flavor_unitcount_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_name',)},
        ),
    ]
