# Generated by Django 4.1.3 on 2022-11-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyomgen', '0003_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('brand_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='flavor',
            unique_together={('flavor_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='unitcount',
            unique_together={('unit_count_name',)},
        ),
    ]
