# Generated by Django 4.1.3 on 2022-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyomgen', '0004_alter_brand_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyomgenproduct',
            name='drs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
